apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: profile-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apps-haimoney-staging
      io.kompose.service: profile-db
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apps-haimoney-staging
        io.kompose.service: profile-db
    spec:
      containers:
        - name: profile-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: profiles
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: profile-db
              mountPath: /var/lib/postgresql/data
              subPath: data
            - name: app-log-directory
              mountPath: /app-logs
      volumes:
        - name: profile-db
          persistentVolumeClaim:
            claimName: profile-db
        - name: app-log-directory
          emptyDir: {} 