apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-processing-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: file-processing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-processing-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: file-processing-service
    spec:
      containers:
      - name: file-processing-service
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/file-processing-service:v0.0.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
          protocol: TCP
        volumeMounts:
        - mountPath: /data/files
          name: file-processing-storage
        - mountPath: /app-logs
          name: app-log-directory
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: file-processing-storage
        persistentVolumeClaim:
          claimName: file-processing-storage
      - emptyDir: {}
        name: app-log-directory 