apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-queue
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: event-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: event-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: event-queue
    spec:
      containers:
      - name: event-queue
        image: rabbitmq:3-management
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 15672
          protocol: TCP
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      volumes:
      - emptyDir: {}
        name: app-log-directory 