apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcti-worker-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-worker-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: rcti-worker-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: rcti-worker-service
    spec:
      containers:
      - name: rcti-worker-service
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-worker-service:v0.0.16
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
          protocol: TCP
        env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-log-directory 