apiVersion: v1
kind: Service
metadata:
  name: rcti-worker-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-worker-service
spec:
  type: ClusterIP
  ports:
  - name: "5010"
    port: 5010
    protocol: TCP
    targetPort: 5001
  selector:
    io.kompose.service: rcti-worker-service 