apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"automation-regcred-updater-prod"},"name":"ecr-registry-helper","namespace":"default"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["/bin/sh","-c","ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`\nNAMESPACE_NAME=default\nkubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME\nkubectl create secret docker-registry $DOCKER_SECRET_NAME \\\n--docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \\\n--docker-username=AWS \\\n--docker-password=\"${ECR_TOKEN}\" \\\n--namespace=$NAMESPACE_NAME\necho \"Secret was successfully updated at $(date)\""],"envFrom":[{"secretRef":{"name":"ecr-registry-helper-secrets"}},{"configMapRef":{"name":"ecr-registry-helper-cm"}}],"image":"odaniait/aws-kubectl:latest","imagePullPolicy":"IfNotPresent","name":"ecr-registry-helper"}],"restartPolicy":"Never","serviceAccountName":"sa-default"}}}},"schedule":"0 */10 * * *","successfulJobsHistoryLimit":3,"suspend":false}}
  creationTimestamp: "2024-11-21T10:08:40Z"
  generation: 1
  name: ecr-registry-helper
  namespace: default
  resourceVersion: "19225443"
  uid: 972ea153-7ee3-4d5a-8d9f-15513cda807c
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - |-
              ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
              NAMESPACE_NAME=default
              kubectl delete secret --ignore-not-found $DOCKER_SECRET_NAME -n $NAMESPACE_NAME
              kubectl create secret docker-registry $DOCKER_SECRET_NAME \
              --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
              --docker-username=AWS \
              --docker-password="${ECR_TOKEN}" \
              --namespace=$NAMESPACE_NAME
              echo "Secret was successfully updated at $(date)"
            envFrom:
            - secretRef:
                name: ecr-registry-helper-secrets
            - configMapRef:
                name: ecr-registry-helper-cm
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            name: ecr-registry-helper
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: sa-default
          serviceAccountName: sa-default
          terminationGracePeriodSeconds: 30
  schedule: 0 */10 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2025-03-17T10:00:00Z"
  lastSuccessfulTime: "2025-03-17T10:00:07Z"
