apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: loan-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apps-haimoney-staging
      io.kompose.service: loan-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apps-haimoney-staging
        io.kompose.service: loan-db
    spec:
      containers:
        - name: loan-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: loan
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: loan-service-data
              mountPath: /var/lib/postgresql/data
              subPath: data
            - name: app-log-directory
              mountPath: /app-logs
      volumes:
        - name: loan-service-data
          persistentVolumeClaim:
            claimName: loan-service-data
        - name: app-log-directory
          emptyDir: {} 