apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: gateway-service
spec:
  type: ClusterIP
  ports:
  - name: "5001"
    port: 5001
    protocol: TCP
    targetPort: 5001
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: gateway-service 