apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcti-backend-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-backend-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: rcti-backend-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: rcti-backend-service
    spec:
      containers:
      - name: rcti-backend-service
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-backend-service:v0.0.15
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: DSN
          value: host=rcti-file-db port=5432 user=postgres password=postgres dbname=rcti_file_entries sslmode=disable timezone=UTC connect_timeout=5
        - name: FILE_DIRECTORY
          value: /data/files/
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/files
          name: rcti-file-storage
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rcti-file-storage
        persistentVolumeClaim:
          claimName: rcti-file-storage
      - emptyDir: {}
        name: app-log-directory 