apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment-v16.yaml
- service.yaml
- pvc.yaml

commonLabels:
  app.kubernetes.io/instance: apps-haimoney-staging
  io.kompose.service: rcti-backend-service 