apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rcti-file-storage
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-backend-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn 