apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-worker
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: de-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: de-worker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: de-worker
    spec:
      containers:
      - name: de-worker
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/de-worker:v0.0.15
        imagePullPolicy: IfNotPresent
        env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        - name: BROKER_URI
          value: broker-service:5001
        - name: DE_BACKEND_URI
          value: de-backend-service:5001
        - name: FINANCIAL_URI
          value: financial-service:5001 # this is not used
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      imagePullSecrets:
      - name: regcred
      volumes:
      - emptyDir: {}
        name: app-log-directory 