apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: profile-service
spec:
  ports:
  - name: "5001"
    port: 5001
    targetPort: 5001
    protocol: TCP
  selector:
    io.kompose.service: profile-service 