apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: auth-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: auth-service
    spec:
      containers:
      - name: auth-service
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/auth-service:v0.0.34
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
          protocol: TCP
        env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        - name: APP_URL
          value: https://staging.haimoney.com.au
        - name: DB_HOST
          value: auth-db
        - name: DB_NAME
          value: user
        - name: DB_PORT
          value: "5432"
        - name: DB_PW
          value: postgres
        - name: DB_USER
          value: postgres
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: jwt-secret-key
        - name: SUBSCRIBER_TOPIC
          value: auth.any
        - name: TOKEN_COOKIE_NAME
          value: x-ut-chunk
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-log-directory 