apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-key
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
type: Opaque
data:
  jwt-secret: Q3Z5ZDF6UDY2VlRjej9DZGpUZS5PZUpXYWtZb1VYQmU= 