apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: auth-service
spec:
  type: ClusterIP
  ports:
  - name: "5001"
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    io.kompose.service: auth-service 