apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcti-file-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-file-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apps-haimoney-staging
      io.kompose.service: rcti-file-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apps-haimoney-staging
        io.kompose.service: rcti-file-db
    spec:
      containers:
        - name: rcti-file-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: rcti_file_entries
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: rcti-db-data
              mountPath: /var/lib/postgresql/data
              subPath: data
            - name: app-log-directory
              mountPath: /app-logs
      volumes:
        - name: rcti-db-data
          persistentVolumeClaim:
            claimName: rcti-db-data
        - name: app-log-directory
          emptyDir: {} 