apiVersion: v1
kind: Service
metadata:
  name: broker-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: broker-db
spec:
  ports:
    - name: "5432"
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    io.kompose.service: broker-db
  type: ClusterIP 