apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/instance: apps-haimoney-staging
  io.kompose.service: auth-db 