apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-file-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: de-file-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: apps-haimoney-staging
      io.kompose.service: de-file-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: apps-haimoney-staging
        io.kompose.service: de-file-db
    spec:
      containers:
        - name: de-file-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "de_file_entries"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: de-db-data
              subPath: data
            - mountPath: /app-logs
              name: app-log-directory
      volumes:
        - name: de-db-data
          persistentVolumeClaim:
            claimName: de-db-data
        - emptyDir: {}
          name: app-log-directory 