apiVersion: v1
kind: Service
metadata:
  name: de-file-db
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: de-file-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: de-file-db 