apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"apps-haimoney-staging","io.kompose.service":"rcti-backend-service"},"name":"rcti-backend-service","namespace":"default"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"io.kompose.service":"rcti-backend-service"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"io.kompose.service":"rcti-backend-service"}},"spec":{"containers":[{"env":[{"name":"DSN","value":"host=rcti-file-db port=5432 user=postgres password=postgres dbname=rcti_file_entries sslmode=disable timezone=UTC connect_timeout=5"},{"name":"FILE_DIRECTORY","value":"/data/files/"}],"image":"324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-backend-service:v0.0.15","imagePullPolicy":"IfNotPresent","name":"rcti-backend-service","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"512Mi"},"requests":{"cpu":"100m","memory":"256Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/data/files","name":"rcti-file-storage"},{"mountPath":"/app-logs","name":"app-log-directory"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"rcti-file-storage","persistentVolumeClaim":{"claimName":"rcti-file-storage"}},{"emptyDir":{},"name":"app-log-directory"}]}}}}
  creationTimestamp: "2024-11-21T10:54:21Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: rcti-backend-service
  name: rcti-backend-service
  namespace: default
  resourceVersion: "20003309"
  uid: 169aeaa8-ea7c-4a66-8b19-00a30ac88725
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: rcti-backend-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rcti-backend-service
    spec:
      containers:
      - env:
        - name: DSN
          value: host=rcti-file-db port=5432 user=postgres password=postgres dbname=rcti_file_entries
            sslmode=disable timezone=UTC connect_timeout=5
        - name: FILE_DIRECTORY
          value: /data/files/
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-backend-service:v0.0.15
        imagePullPolicy: IfNotPresent
        name: rcti-backend-service
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/files
          name: rcti-file-storage
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rcti-file-storage
        persistentVolumeClaim:
          claimName: rcti-file-storage
      - emptyDir: {}
        name: app-log-directory
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-27T08:15:12Z"
    lastUpdateTime: "2025-02-27T08:15:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-11-21T10:54:43Z"
    lastUpdateTime: "2025-03-22T06:03:08Z"
    message: ReplicaSet "rcti-backend-service-6cc478b4d5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
