apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    kompose.cmd: kompose -f ../docker-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose -f ../docker-compose.yaml convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"app.kubernetes.io/instance":"apps-haimoney-prod","io.kompose.service":"mail-service"},"name":"mail-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"mail-service"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose -f ../docker-compose.yaml convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"io.kompose.service":"mail-service"}},"spec":{"containers":[{"env":[{"name":"AMQP_URI","value":"amqp://guest:guest@event-queue:5672/"},{"name":"DOMAIN_NAME","value":"comprosys-test.com"}],"image":"324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/mail-service:v0.0.13","imagePullPolicy":"IfNotPresent","name":"mail-service","volumeMounts":[{"mountPath":"/app-logs","name":"app-log-directory"}]}],"imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","volumes":[{"emptyDir":{},"name":"app-log-directory"}]}}}}
  creationTimestamp: "2024-11-21T10:54:19Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: apps-haimoney-prod
    io.kompose.service: mail-service
  name: mail-service
  namespace: default
  resourceVersion: "16291702"
  uid: 9df197e9-3eeb-45df-b070-d6b17f8ad854
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: mail-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../docker-compose.yaml convert
        kompose.version: 1.34.0 (cbf2835db)
      creationTimestamp: null
      labels:
        io.kompose.service: mail-service
    spec:
      containers:
      - env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        - name: SMTP_SERVER_URI
          value: smtp.mandrillapp.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USERNAME
          value: Hai Money
        - name: SMTP_PASSWORD
          value: md-2NfG28X9NO0LPUGFDToGPA
        - name: SMTP_SENDER_NAME
          value: Hai Money Commissions
        - name: SMTP_FROM_ADDRESS
          value: commissions@haimoney.com.au
        - name: SMTP_REPLY_TO_ADDRESS
          value: commissions@haimoney.com.au
        - name: DEV_MODE
          value: "false"
        - name: ENABLE_MAIL_SENDING
          value: "true"
        - name: LOG_DIR
          value: "/app-logs"
        - name: RPC_PORT
          value: "5001"
        - name: TEST_EMAIL_ADDRESS
          value: liw85388@gmail.com
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/mail-service:v0.1.0
        imagePullPolicy: IfNotPresent
        name: mail-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-log-directory
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-21T10:54:35Z"
    lastUpdateTime: "2024-11-25T23:41:01Z"
    message: ReplicaSet "mail-service-86597f5b96" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-27T08:24:37Z"
    lastUpdateTime: "2025-02-27T08:24:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
