apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kompose.cmd: kompose -f ./docker-compose.yaml -o ./kube convert
    kompose.version: 1.34.0 (cbf2835db)
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"kompose.cmd":"kompose -f ./docker-compose.yaml -o ./kube convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"app.kubernetes.io/instance":"apps-haimoney-prod","io.kompose.service":"rcti-worker-service"},"name":"rcti-worker-service","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"io.kompose.service":"rcti-worker-service"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"annotations":{"kompose.cmd":"kompose -f ./docker-compose.yaml -o ./kube convert","kompose.version":"1.34.0 (cbf2835db)"},"labels":{"io.kompose.service":"rcti-worker-service"}},"spec":{"containers":[{"env":[{"name":"AMQP_URI","value":"amqp://guest:guest@event-queue:5672/"}],"image":"324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-worker-service:v0.0.13","imagePullPolicy":"IfNotPresent","name":"rcti-worker-service","ports":[{"containerPort":5001,"protocol":"TCP"}],"volumeMounts":[{"mountPath":"/app-logs","name":"app-log-directory"}]}],"imagePullSecrets":[{"name":"regcred"}],"restartPolicy":"Always","volumes":[{"emptyDir":{},"name":"app-log-directory"}]}}}}
  creationTimestamp: "2024-11-21T10:54:21Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: apps-haimoney-prod
    io.kompose.service: rcti-worker-service
  name: rcti-worker-service
  namespace: default
  resourceVersion: "16291814"
  uid: e76afe30-0506-4d37-827b-d8979d7c2943
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: rcti-worker-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./docker-compose.yaml -o ./kube convert
        kompose.version: 1.34.0 (cbf2835db)
      creationTimestamp: null
      labels:
        io.kompose.service: rcti-worker-service
    spec:
      containers:
      - env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/rcti-worker-service:v0.0.16
        imagePullPolicy: IfNotPresent
        name: rcti-worker-service
        ports:
        - containerPort: 5001
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-log-directory
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-11-21T10:54:46Z"
    lastUpdateTime: "2024-11-26T04:44:38Z"
    message: ReplicaSet "rcti-worker-service-566b5dd668" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-02-27T08:24:45Z"
    lastUpdateTime: "2025-02-27T08:24:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
