apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: default
  labels:
    app.kubernetes.io/instance: apps-haimoney-staging
    io.kompose.service: mail-service
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: mail-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: mail-service
    spec:
      containers:
      - name: mail-service
        image: 324037285736.dkr.ecr.ap-southeast-2.amazonaws.com/haimoney/mail-service:v0.0.15
        imagePullPolicy: IfNotPresent
        env:
        - name: AMQP_URI
          value: amqp://guest:guest@event-queue:5672/
        - name: SMTP_SERVER_URI
          value: smtp.mandrillapp.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USERNAME
          value: Hai Money
        - name: SMTP_PASSWORD
          value: md-2NfG28X9NO0LPUGFDToGPA
        - name: SMTP_SENDER_NAME
          value: Hai Money Commissions
        - name: SMTP_FROM_ADDRESS
          value: commissions@haimoney.com.au
        - name: SMTP_REPLY_TO_ADDRESS
          value: commissions@haimoney.com.au
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app-logs
          name: app-log-directory
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-log-directory 